#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_


//#define PLATFORM_EMAC_BASEADDR XPAR_ETHERNET_BASEADDR

#define PLATFORM_EMAC_BASEADDR XPAR_AXIETHERNET_0_BASEADDR

//#define PLATFORM_TIMER_BASEADDR XPAR_TIMER_BASEADDR
//#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_CPU_AXI_INTC_TIMER_INTERRUPT_INTR
//#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_CPU_AXI_INTC_TIMER_INTERRUPT_INTR)

#define PLATFORM_TIMER_BASEADDR XPAR_AXI_TIMER_0_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_INTR
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_INTR)

#define STDOUT_IS_16550
#define STDOUT_BASEADDR XPAR_AXI_UART16550_0_BASEADDR

#endif
